/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import Entity.Controller;
import Entity.Nhanvien;
import Untils.DateUtils;
import Untils.XuLy;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.font.TextAttribute;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class FormDangNhap extends javax.swing.JFrame {

    /**
     * Creates new form FormDangNhap
     */
    Controller<Nhanvien> ketNoi = new Controller<>(Nhanvien.class);
    public FormDangNhap() {
        initComponents();
        lblChangePassword.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Font originalFont = lblChangePassword.getFont();
        
        Map<TextAttribute, Object> fontAttributes = (Map<TextAttribute, Object>) originalFont.getAttributes();
        fontAttributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON); // Đặt gạch chân
        lblChangePassword.setFont(originalFont.deriveFont(fontAttributes));
        
        // Thêm MouseListener để thay đổi màu chữ khi di chuột vào và ra khỏi JLabel
        lblChangePassword.addMouseListener(new MouseAdapter() {
            
            public void mouseEntered(MouseEvent e) {
                lblChangePassword.setForeground(Color.BLUE); // Đổi màu chữ thành xanh khi di chuột vào
            }

            
            public void mouseExited(MouseEvent e) {
                lblChangePassword.setForeground(Color.BLACK); // Đổi màu chữ lại thành đen khi di chuột ra
            }
        });
    }
    
    void check() {
        if(checkRong() == false) {
            JOptionPane.showMessageDialog(this, "Yêu cầu nhập đủ thông tin");
            return;
       }
        
        String maNV = txtMaNV.getText();
        String matKhau = new String(txtPass.getPassword());
        
        Nhanvien nv = ketNoi.findById(Integer.parseInt(maNV));
        
        if (nv != null) {
            // Nếu mã nhân viên tồn tại, kiểm tra mật khẩu
            if (nv.getMatKhau().equals(matKhau)) {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                // Thực hiện hành động tiếp theo sau khi đăng nhập thành công
//                Menu newMenu = new Menu();
//                newMenu.setVisible(true);
//                XuLy.taiKhoanNhanVien = ketNoi_NhanVien.findById(Integer.parseInt(tenDN));
//                
//                this.setVisible(false);
                
            } else {
                JOptionPane.showMessageDialog(this, "Sai mật khẩu!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập không tồn tại!");
        }
       
    }
    
    boolean checkRong() {
        if(txtMaNV.getText().isEmpty())
            return false;
        if(new String(txtPass.getPassword()).isEmpty())
            return false;
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        lblChangePassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mã nhân viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mật khẩu");

        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblChangePassword.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        lblChangePassword.setText("Đổi mật khẩu");
        lblChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChangePasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaNV)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(lblChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblChangePassword)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        check();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangePasswordMouseClicked
        if(!txtMaNV.getText().isEmpty()) {
            String maNV = txtMaNV.getText();
            String matKhau = new String(txtPass.getPassword());

            Nhanvien nv = ketNoi.findById(Integer.parseInt(maNV));
            if (nv != null) {
                // Nếu mã nhân viên tồn tại, đổi mật khẩu
                nv.setMaNV(Integer.parseInt(maNV));
                nv.setHoTenNV(nv.getHoTenNV());
                nv.setGioiTinh(nv.getGioiTinh());
                Date ngaysinh= DateUtils.parseDate(nv.getNgaySinh());
                nv.setNgaySinh(ngaysinh);
                nv.setSdt(nv.getSdt());
                nv.setEmail(nv.getEmail());
                nv.setMatKhau(matKhau);
                ketNoi.sua(nv);
                JOptionPane.showMessageDialog(this, "Sửa mật khẩu thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Tên đăng nhập không tồn tại!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Yêu cầu nhập tên đăng nhập!");
        }
    }//GEN-LAST:event_lblChangePasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblChangePassword;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
