/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import Entity.Controller;
import Entity.Nhanvien;
import Untils.DateUtils;
import Untils.XuLy;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.font.TextAttribute;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class FormDangNhap extends javax.swing.JFrame {

    /**
     * Creates new form FormDangNhap
     */
    Controller<Nhanvien> ketNoi = new Controller<>(Nhanvien.class);
    public FormDangNhap() {
        initComponents();
        lblQuenMK.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Font originalFont = lblQuenMK.getFont();
        
        Map<TextAttribute, Object> fontAttributes = (Map<TextAttribute, Object>) originalFont.getAttributes();
        fontAttributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON); // Đặt gạch chân
        lblQuenMK.setFont(originalFont.deriveFont(fontAttributes));
        
        // Thêm MouseListener để thay đổi màu chữ khi di chuột vào và ra khỏi JLabel
        lblQuenMK.addMouseListener(new MouseAdapter() {
            
            public void mouseEntered(MouseEvent e) {
                lblQuenMK.setForeground(Color.BLUE); // Đổi màu chữ thành xanh khi di chuột vào
            }

            
            public void mouseExited(MouseEvent e) {
                lblQuenMK.setForeground(Color.BLACK); // Đổi màu chữ lại thành đen khi di chuột ra
            }
        });
    }
    
    void check() {
        if(checkRong() == false) {
            JOptionPane.showMessageDialog(this, "Yêu cầu nhập đủ thông tin");
            return;
       }
        
        String maNV = txtMaNV.getText();
        String matKhau = new String(txtPass.getPassword());
        
        Nhanvien nv = ketNoi.findById(Integer.parseInt(maNV));
        
        if (nv != null) {
            // Nếu mã nhân viên tồn tại, kiểm tra mật khẩu
            if (nv.getMatKhau().equals(matKhau)) {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                // Thực hiện hành động tiếp theo sau khi đăng nhập thành công
                Formmenu newMenu = new Formmenu();
                newMenu.setVisible(true);
                XuLy.taiKhoanNhanVien = nv;
                
                this.setVisible(false);
                
            } else {
                JOptionPane.showMessageDialog(this, "Sai mật khẩu!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập không tồn tại!");
        }
       
    }
    
    boolean checkRong() {
        if(txtMaNV.getText().isEmpty())
            return false;
        if(new String(txtPass.getPassword()).isEmpty())
            return false;
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMK = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        btnDN = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        lblQuenMK = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mã nhân viên");

        lblMK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMK.setText("Mật khẩu");

        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnDN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDN.setText("Đăng nhập");
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblQuenMK.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        lblQuenMK.setText("Quên mật khẩu?");
        lblQuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDN, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMK, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaNV)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(lblQuenMK, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuenMK)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        if (btnDN.getText() == "Đăng nhập") {
            check();
        }
        else {
            char[] password = txtPass.getPassword();
            if (password != null && password.length > 0) {
                Nhanvien nv = ketNoi.findById(Integer.parseInt(txtMaNV.getText()));
                nv.setMaNV(Integer.parseInt(txtMaNV.getText()));
                nv.setHoTenNV(nv.getHoTenNV());
                nv.setGioiTinh(nv.getGioiTinh());
                Date ngaysinh= DateUtils.parseDate(nv.getNgaySinh());
                nv.setNgaySinh(ngaysinh);
                nv.setSdt(nv.getSdt());
                nv.setEmail(nv.getEmail());
                nv.setMatKhau(new String(txtPass.getPassword()));
                ketNoi.sua(nv);
                JOptionPane.showMessageDialog(this, "Sửa mật khẩu thành công!");
                txtPass.setText("");
                btnDN.setText("Đăng nhập");
            }
            else {
                JOptionPane.showMessageDialog(this, "Yêu cầu nhập mật khẩu mới!");
            }
        }
        
    }//GEN-LAST:event_btnDNActionPerformed

    private void lblQuenMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseClicked
        if(!txtMaNV.getText().isEmpty()) {
            String maNV = txtMaNV.getText();
            String matKhau = new String(txtPass.getPassword());

            Nhanvien nv = ketNoi.findById(Integer.parseInt(maNV));
            if (nv != null) {
                // Nếu mã nhân viên tồn tại, đổi mật khẩu
                lblMK.setText("Mật khẩu mới");
                btnDN.setText("Đổi mật khẩu");
            } else {
                JOptionPane.showMessageDialog(this, "Tên đăng nhập không tồn tại!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Yêu cầu nhập tên đăng nhập!");
        }
    }//GEN-LAST:event_lblQuenMKMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (btnDN.getText() == "Đổi mật khẩu") {
            lblMK.setText("Mật khẩu");
            btnDN.setText("Đăng nhập");
        }
        else {
            System.exit(0);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDN;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMK;
    private javax.swing.JLabel lblQuenMK;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
