/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import Entity.Chitietpm;
import Entity.ChitietpmPK;
import Entity.Controller;
import Entity.Phieumuon;
import Entity.Sach;
import Untils.XuLy;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class FormChiTietPhieuMuon extends javax.swing.JFrame {

    /**
     * Creates new form FormChiTietPhieuMuon
     */
    Controller<Chitietpm> ketNoi_CTPM = new Controller<>(Chitietpm.class);
    Controller<Sach> ketNoi_Sach = new Controller<>(Sach.class);
    Controller<Phieumuon> ketNoi_PM = new Controller<>(Phieumuon.class);
    DefaultTableModel model;
    String maPhieuMuon;
    List<Sach> listsach = ketNoi_Sach.getAll();
    
    public FormChiTietPhieuMuon(String maPM) {
        initComponents();
        this.maPhieuMuon = maPM;
        txtMaPM.setText(maPM);
        model = (DefaultTableModel) jTable1.getModel();
        
        for(Sach sach:listsach){
            cboMaSach.addItem(sach.getMaSach()+"-"+sach.getTenSach());
        }
        
        loadData();
        
        Phieumuon pm = ketNoi_PM.findById(Integer.parseInt(maPM));
        if (pm.getTrangThai() == true) {
            btnThem.setEnabled(false);
            btnXoa.setEnabled(false);
        }
    }
    
    void loadData() {
        clear();
        ketNoi_CTPM.loaddataChitet(model, new String[] {"getInforPhieuMuon", 
            "getInforSach", "getSoLuongMuon", "getTinhTrangKhiMuon"}, maPhieuMuon);
    }
    
    void clear() {
        cboMaSach.setSelectedIndex(-1);
        ketNoi_CTPM.clear(new JTextField[] {txtSoLuongMuon, txtTinhTrangKhiMuon}, model);
    } 
    
//    void trusach(){
//        for(Chitietpm chi:chitiet){
//            Sach kho=ketNoi_Sach.findById(chi.getSach().getMaSach());
//            kho.setSoLuong(kho.getSoLuong()-chi.getSoLuongMuon());
//            ketNoi_Sach.sua(kho);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaPM = new javax.swing.JTextField();
        cboMaSach = new javax.swing.JComboBox<>();
        txtSoLuongMuon = new javax.swing.JTextField();
        txtTinhTrangKhiMuon = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CHI TIẾT PHIẾU MƯỢN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Mã phiếu mượn");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Mã sách");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Số lượng mượn");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Tình trạng khi mượn");

        txtMaPM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtMaPM.setEnabled(false);

        cboMaSach.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtSoLuongMuon.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtTinhTrangKhiMuon.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu mượn", "Mã sách", "Số lượng mượn", "Tình trạng khi mượn"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cboMaSach, javax.swing.GroupLayout.Alignment.LEADING, 0, 146, Short.MAX_VALUE)
                    .addComponent(txtMaPM, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTinhTrangKhiMuon, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoLuongMuon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(507, 507, 507)
                        .addComponent(btnThem)
                        .addGap(41, 41, 41)
                        .addComponent(btnXoa)
                        .addGap(51, 51, 51)
                        .addComponent(btnClear)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtSoLuongMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtTinhTrangKhiMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        Chitietpm ct_pm = new Chitietpm();
        
        Phieumuon pm = new Phieumuon(Integer.parseInt(txtMaPM.getText()));
        ct_pm.setPhieumuon(pm);

        Object selectedMaSach = cboMaSach.getSelectedItem();
        int maSach = 0;
        if (selectedMaSach != null) {
            maSach = XuLy.layId(selectedMaSach.toString());

            // Tạo và thiết lập khóa chính cho Chitietphieumuon
            ChitietpmPK chitietphieumuonPK = new ChitietpmPK(Integer.parseInt(txtMaPM.getText()), maSach);
            ct_pm.setChitietpmPK(chitietphieumuonPK);
            ct_pm.setSach(new Sach(maSach));
        }
        try {
            ct_pm.setSoLuongMuon(Integer.parseInt(txtSoLuongMuon.getText()));
            ct_pm.setTinhTrangKhiMuon(txtTinhTrangKhiMuon.getText());
        } 
        catch (NumberFormatException e) {
                XuLy.mesLoi(e, this);
        }
        
        
        int soLuongMuon = Integer.parseInt(txtSoLuongMuon.getText());
        
        Sach kho=ketNoi_Sach.findById(maSach);
        
        if (soLuongMuon > kho.getSoLuong()){
            JOptionPane.showMessageDialog(this, "Không đủ sách");
            return;
        }
        kho.setSoLuong(kho.getSoLuong()-soLuongMuon);
        ketNoi_Sach.sua(kho);
        
        ketNoi_CTPM.addSv(ct_pm);
        loadData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
         
        if (!txtMaPM.getText().isEmpty() && cboMaSach.getSelectedItem() != null) {
            try{
                int soLuongMuon = Integer.parseInt(txtSoLuongMuon.getText());
        
                Sach kho=ketNoi_Sach.findById(XuLy.layId(cboMaSach.getSelectedItem().toString()));

                kho.setSoLuong(kho.getSoLuong()+soLuongMuon);
                ketNoi_Sach.sua(kho);
                ketNoi_CTPM.xoa(new ChitietpmPK(Integer.parseInt(txtMaPM.getText()), 
                        XuLy.layId(cboMaSach.getSelectedItem().toString())));
                clear();
                loadData();
            } catch(Exception e){
               XuLy.mesLoi(e, this);
            }    
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row =jTable1.getSelectedRow();
        if(row>=0){
            txtMaPM.setText(jTable1.getValueAt( row, 0).toString());
            cboMaSach.setSelectedItem(jTable1.getValueAt(row, 1).toString());
            txtSoLuongMuon.setText(jTable1.getValueAt( row, 2).toString());
            txtTinhTrangKhiMuon.setText(jTable1.getValueAt( row, 3).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        loadData();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormChiTietPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormChiTietPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormChiTietPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormChiTietPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormChiTietPhieuMuon().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtMaPM;
    private javax.swing.JTextField txtSoLuongMuon;
    private javax.swing.JTextField txtTinhTrangKhiMuon;
    // End of variables declaration//GEN-END:variables
}
